# Generated by Django 6.0.1 on 2026-01-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('wikipedia_section_title', models.TextField(blank=True, null=True)),
                ('image_filename', models.TextField(blank=True, null=True)),
                ('years', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalSources',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'external_sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarysRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marys_requests',
                'managed': False,
            },
        ),
    ]
